<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework><Nullable>disable</Nullable><ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>gregMod.Trainer</AssemblyName><RootNamespace>GregModTrainer</RootNamespace><Platforms>x64</Platforms><AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Version>1.0.3</Version><AssemblyVersion>1.0.3.0</AssemblyVersion><FileVersion>1.0.3.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="MelonLoader" HintPath="references/MelonLoader.dll" Private="false" />
    <Reference Include="0Harmony" HintPath="references/0Harmony.dll" Private="false" />
    <Reference Include="Il2CppInterop.Runtime" HintPath="references/Il2CppInterop.Runtime.dll" Private="false" />
    <Reference Include="Il2Cppmscorlib" HintPath="references/Il2Cppmscorlib.dll" Private="false" />
    <Reference Include="Assembly-CSharp" HintPath="references/Assembly-CSharp.dll" Private="false" />
    <Reference Include="UnityEngine.CoreModule" HintPath="references/UnityEngine.CoreModule.dll" Private="false" />
    <Reference Include="UnityEngine.IMGUIModule" HintPath="references/UnityEngine.IMGUIModule.dll" Private="false" />
    <Reference Include="UnityEngine.UIModule" HintPath="references/UnityEngine.UIModule.dll" Private="false" />
    <Reference Include="UnityEngine.TextRenderingModule" HintPath="references/UnityEngine.TextRenderingModule.dll" Private="false" />
    <Reference Include="UnityEngine.dll" HintPath="references/UnityEngine.dll" Private="false" />
    <Reference Include="Unity.InputSystem" HintPath="references/Unity.InputSystem.dll" Private="false" />
    <Reference Include="UnityEngine.UIElementsModule" HintPath="references/UnityEngine.UIElementsModule.dll" Private="false" />
    <Reference Include="UnityEngine.UI" HintPath="references/UnityEngine.UI.dll" Private="false" />
    <Reference Include="gregCore" HintPath="references/gregCore.dll" Private="false" />
  </ItemGroup>
</Project>